### ISSUE TITLE
Nagios/Icinga

### ISSUE THREAD

**Issue by pcdog** [heximcz/mxtoolbox#1]
Hey, 

can you create it in a form that the output is already unstandable by icinga/nagios?

Cool would be warning = 1 Entry, Critical = 2+ Entries

WDYT?

**Comment by heximcz** [comment]
Hi,
script goal is to be the library. However, I can prepare some examples how to use this for Icinga and Nagios.

**Comment by pcdog** [comment]
OK; I can prepare some icinga script otherwise and use your library ;) let me see... my code will be ugly so you can make it better then :)

**Comment by heximcz** [comment]
Can you try this example in Nagios ? [nagiosUsage.php](https://github.com/heximcz/mxtoolbox/blob/master/examples/nagiosUsage.php) I have no place to try it, I do not have Nagios installed.
